model:
  type: "CNN"
  input_shape: [224, 224, 3]
  layers:
    - type: "Conv2D"
      filters: 32
      kernel_size: 3
      activation: "relu"
      padding: "same"
    - type: "MaxPooling2D"
      pool_size: 2
    - type: "Conv2D"
      filters: 64
      kernel_size: 3
      activation: "relu"
      padding: "same"
    - type: "MaxPooling2D"
      pool_size: 2
    - type: "Conv2D"
      filters: 128
      kernel_size: 3
      activation: "relu"
      padding: "same"
    - type: "MaxPooling2D"
      pool_size: 2
    - type: "Flatten"
    - type: "Dense"
      units: 128
      activation: "relu"
    - type: "Dense"
      units: 1
      activation: "sigmoid"

training:
  batch_size: 32
  learning_rate: 0.001
  epochs: 50
  optimizer: "adam"
  loss_function: "binary_crossentropy"

anomaly_types:
  - "type1"
  - "type2"
  - "type3"